import deepReplace from './deep-replace';
import { forEachItems, forEachVariables, normaliseVariables } from './variables';
import { isRegistrySource, resolveRegistryItems } from './registry';
import { CONSUMER_TYPES } from './templates';
import { VariablesConfig } from './types';

/* eslint-disable @typescript-eslint/no-explicit-any */

/*
 * A view that builds itself. A card can only repeat inside the one slot it was given, so a
 * repeat over the house's rooms lands in a single section however wide the screen is - the
 * sections never reflow, and none of them gets a heading or a background of its own. Home
 * Assistant lets a view be generated by a strategy instead, and a generated view is laid
 * out by Home Assistant like any other. So the strategy writes the view out - a section,
 * or a badge, per item - and Home Assistant does the rest.
 *
 *   strategy:
 *     type: custom:decluttering-card-plus
 *     sections:
 *       - for_each_from: { areas: true }
 *         section:
 *           type: grid
 *           cards:
 *             - type: heading
 *               heading: '[[name]]'
 *             - type: custom:decluttering-card-plus
 *               template: room_lights
 *
 * An entry with nothing to repeat over is passed through as written, so a repeat sits
 * among ordinary sections and badges. Everything else in the strategy is the view's own.
 */

/** The strategy's own keys - the rest of what it says is the view. */
const OWN_KEYS = ['type', 'variables', 'sections', 'badges'];

/** Whether an entry asks to be repeated, rather than being a section or badge as written. */
export function isRepeatEntry(entry: any): boolean {
  if (!entry || typeof entry !== 'object' || Array.isArray(entry)) return false;
  return entry.for_each !== undefined || entry.for_each_from !== undefined;
}

/** The items an entry repeats over - a list written out, or what Home Assistant knows. */
function entryItems(entry: any, hass: any): unknown[] {
  const written = forEachItems(entry.for_each);
  if (written) return written;
  return isRegistrySource(entry.for_each_from) ? resolveRegistryItems(hass, entry.for_each_from) : [];
}

/*
 * A templated card inside a copy is handed that copy's values too, so a section can hold
 * `template: room_lights` and nothing else - the area it is for arrives on its own. The
 * card's own values come first, so anything it says for itself still wins. A template
 * card's content is never touched: that is a definition, not a use.
 */
function handDown(node: any, values: VariablesConfig[]): any {
  if (Array.isArray(node)) return node.map((item) => handDown(item, values));
  if (!node || typeof node !== 'object') return node;
  if (CONSUMER_TYPES.includes(node.type)) {
    return { ...node, variables: [...normaliseVariables(node.variables), ...values] };
  }
  const out: any = {};
  for (const [key, value] of Object.entries(node)) out[key] = handDown(value, values);
  return out;
}

/**
 * One entry of `sections:` or `badges:`, as the list of sections or badges it stands for:
 * itself when it repeats nothing, one copy per item when it does, and its `empty:` when a
 * repeat matches nothing at all.
 */
export function expandEntry(entry: any, kind: 'section' | 'badge', shared: unknown, hass?: any): any[] {
  if (!isRepeatEntry(entry)) return [entry];
  const content = entry[kind];
  if (content === undefined) return [];

  const items = entryItems(entry, hass);
  if (!items.length) return entry.empty === undefined ? [] : [entry.empty];

  const common = [...normaliseVariables(entry.variables), ...normaliseVariables(shared)];
  return items.map((item, index) => {
    const values = forEachVariables(item, common, index, items.length);
    return handDown(deepReplace(values, {}, content, undefined, hass), values);
  });
}

/** The view a strategy config describes, with every repeat written out. */
export function generateView(config: any, hass?: any): any {
  const view: any = {};
  for (const [key, value] of Object.entries(config ?? {})) {
    if (!OWN_KEYS.includes(key)) view[key] = value;
  }

  const expand = (list: unknown, kind: 'section' | 'badge'): any[] =>
    ([] as any[]).concat(
      ...(Array.isArray(list) ? list : []).map((entry: any) => expandEntry(entry, kind, config?.variables, hass)),
    );

  if (config?.badges !== undefined) view.badges = expand(config.badges, 'badge');
  if (config?.sections !== undefined) {
    view.sections = expand(config.sections, 'section');
    // Sections only mean anything in a sections view, so that is what asking for them gets.
    view.type ??= 'sections';
  }
  return view;
}

/** Whether a repeat in the strategy reads labels, which have to be fetched before it runs. */
export function wantsLabels(config: any): boolean {
  return /label/i.test(JSON.stringify([config?.sections, config?.badges]));
}
